### ISSUE TITLE
could you add a copyright/license please?

### ISSUE THREAD

**Issue by sthen** [fazalmajid/pingwatch#20]
Hi Fazal, this is really neat, I'm interested in adding it to OpenBSD ports. Would you consider adding a copyright and license please?

**Comment by fazalmajid** [comment]
Thanks for your interest.

I am actually working on an OpenBSD port at the moment, using pledge and unveil to limit access since it has to be started as root to be allowed to open raw sockets to send ICMP messages. It's crashing at the moment but I should have it working in a week or two.

I thought I had added a 2-clause BSD license already, but clearly not. I will fix that now.
